### ISSUE TITLE
access token passed in url problem 

### ISSUE THREAD

**Issue by AronWater** [PrincewillIroka/login-with-github#6]
https://github.com/PrincewillIroka/login-with-github/blob/cb39c5eff86123038d8fe8ebc4825ad05ecfbfcf/server/index.js#L41

`Deprecation Notice: GitHub will discontinue authentication to the API using query parameters. Authenticating to the API should be done with HTTP basic authentication. Using query parameters to authenticate to the API will no longer work on May 5, 2021. For more information, including scheduled brownouts, see the blog post.`

Probably because of security issue,     passing access token in the url is no longer supported by github,
please kindly put the access token in the authorization header

**Comment by AronWater** [comment]
since there is no point in passing the scope and token_type (useless parameter)

An example that is working could be like (tested successfully in my computer)

```
return fetch(
              `https://api.github.com/user`,{
                    headers: {
                        Authorization: `token ${access_token}`
                    }
                }
            );
```

**Comment by PrincewillIroka** [comment]
@AronWater thanks for the info. I've fixed it and pushed new changes.
